// <auto-generated />
namespace WpfApp_3SemesterApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddFieldCategoryId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFieldCategoryId));
        
        string IMigrationMetadata.Id
        {
            get { return "202102211402029_AddFieldCategoryId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
